config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show, :destroy, :create, :update]

  root 'home#index'

  resources :courses do
  	resources :details
  end

  match '/users/:id',     to: 'users#show', via: 'get'
  match '/users',     to: 'users#index', via: 'get'
  match '/users/:id',     to: 'users#destroy', via: 'delete'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.role == "Admin"
      can :manage, :all

    elsif user.role == "Dosen"
      can :manage, Course
      can :read, Detail

    elsif user.role == "Mahasiswa"
      can :read, Course
      can :manage, Detail
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :details, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
 
  def new
    @course = Course.new
  end
 
  def edit
    @course = Course.find(params[:id])
  end
 
  def create
    @course = Course.new(course_params)
 
    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end
 
  def update
    @course = Course.find(params[:id])
 
    if @course.update(course_params)
      redirect_to @course
    else
      render 'edit'
    end
  end
 
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
 
    redirect_to course_path
  end
 
  private
    def course_params
      params.require(:course).permit(:title, :code)
    end

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  def create
    
    @course = Course.find(params[:course_id])
    @details = Detail.all
    
    exist = false;

    for detail in @details
      if detail.registered == current_user.email
        exist = true;
      end
    end

    if exist == false
      @detail = @course.details.create(detail_params)
      redirect_to course_path(@course)
    else
      flash[:alert] = "you are already enrolled in this class"
      redirect_to course_path(@course)
    end
  end
 
  def destroy
    @course = Course.find(params[:course_id])
    @detail = @course.comments.find(params[:id])
    @details.destroy
    redirect_to course_path(@course)
  end
 
  private
    def detail_params
      params.require(:detail).permit(:registered)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  	@user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.email == current_user.email

      redirect_to users_path
      flash[:alert] = "You can't delete your own account"
    else
      if @user.destroy
 	    redirect_to users_path
 	  end
  	end
  end

  def update
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/edit.html.erb
<h1>Editing Course</h1>
 
<%= form_for :course, url: course_path(@course), method: :patch do |f| %>
 
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited
        this course from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :code %><br>
    <%= f.text_area :code %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
  <%= menu_group do %>
      
      <%= menu_item "Dashboard", root_path %>

      <%= menu_item "Courses", courses_path %>

      <% if can? :manage, User %>
          <%= menu_item "Manage User", users_path %>
      <% end %>
      
      <%= menu_item "Logout", destroy_user_session_path , :method => :delete %>
  <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h1>Manage Courses</h1>
  </div>
  
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h5>Welcome, <%= current_user.email %> </h5>
  </div>
  
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Code</th>
          <th colspan="3">Action</th>
        </tr>
      </thead>

      <tbody>
        <% @courses.each do |course| %>
        <tr>
          <td><%= course.title %></td>
          <td><%= course.code %></td>
          <% if can? :read, Course %>
            <td><%= link_to 'Show', course %></td>
          <% end %>

          <% if can? :update, Course %>
            <td><%= link_to 'Edit', edit_course_path(course) %></td>
          <% end %>

          <% if can? :destroy, Course %>
            <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="col-md-2"></div>
</div>


<br>
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    
    <% if can? :create, Course %>
      <%= link_to 'New Course', new_course_path, :class => "btn btn-success" %>
    <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

app/views/courses/new.html.erb
<br>
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
  <%= menu_group do %>
      
      <%= menu_item "Dashboard", root_path %>

      <%= menu_item "Courses", courses_path %>

      <% if can? :manage, User %>
          <%= menu_item "Manage User", users_path %>
      <% end %>
      
      <%= menu_item "Logout", destroy_user_session_path , :method => :delete %>
  <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

<br>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h3>Add New Course</h3>
  </div>
  
  <div class="col-md-2"></div>
</div>

<br>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <form>
      <%= form_for :course, url: courses_path do |f| %>
      <% if @course.errors.any? %>
        <div id="error_explanation" class="bg-warning">
          <h2>
            <%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:
          </h2>
          <ul>
            <% @course.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, :placeholder => "Course title" %>
      </div>
      <div class="form-group">
        <%= f.label :code %><br>
        <%= f.text_field :code, :placeholder => "Course code" %>
      </div>
      <%= f.submit :Submit, class: 'btn btn-success' %>
      <%= link_to 'Cancel', courses_path , :class => "btn btn-warning"%>
    <form>
    <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

app/views/courses/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
  <%= menu_group do %>
      
      <%= menu_item "Dashboard", root_path %>

      <%= menu_item "Courses", courses_path %>

      <% if can? :manage, User %>
          <%= menu_item "Manage User", users_path %>
      <% end %>
      
      <%= menu_item "Logout", destroy_user_session_path , :method => :delete %>
  <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

<br>
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <table class="table">
      <tbody>
        <tr>
          <th>Title</th>
          <td><%= @course.title %></td>
        </tr>
        <tr>
          <th>Code</th>
          <td><%= @course.code %> </td>
        </tr>
      </tbody>
    </table>

    <% if can? :update, Course %> 
      <%= link_to 'Edit', edit_course_path(@course), :class => "btn btn-primary"%>
    <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

<br>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h4>Registered Student</h4>
  </div>
  
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Email</th>
        </tr>
      </thead>

      <tbody>
        <% @course.details.each do |detail| %>
        <tr>
          <td><%= detail.registered %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <%= form_for([@course, @course.details.build]) do |f| %>
      <%= f.hidden_field :registered, :value => current_user.email %>
      <%= f.submit  :Join, class: 'btn btn-success'%>
    <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

app/views/home/index.html.erb
<br>>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
	<%= menu_group do %>

      <%= menu_item "Dashboard", root_path %>
      
      <%= menu_item "Courses", courses_path %>

      <% if can? :manage, User %>
          <%= menu_item "Manage User", users_path %>
      <% end %>
      
      <%= menu_item "Logout", destroy_user_session_path , :method => :delete %>
	<% end %>    
  </div>
  
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h1>Dashboard</h1>
  </div>
  
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h5>Welcome <%= @user.email %></h5>
  </div>
  
  <div class="col-md-2"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portaluc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<br>
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
  <%= menu_group do %>
      
      <%= menu_item "Dashboard", root_path %>

      <%= menu_item "Courses", courses_path %>

      <% if can? :manage, User %>
          <%= menu_item "Manage User", users_path %>
      <% end %>
      
      <%= menu_item "Logout", destroy_user_session_path , :method => :delete %>
  <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>

<br>
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h3>Manage Users</h3>
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
  </div>
  
  <div class="col-md-2"></div>
</div>


<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th>Role</th>
        </tr>
      </thead>

      <tbody>
        <% for user in @users %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= link_to 'Show', user%></td>
          <td><%= link_to 'Destroy', user, method: :delete %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="col-md-2"></div>
</div>

app/views/users/show.html.erb
<br>>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8" class="bg-primary">
	<%= menu_group do %>

      <%= menu_item "Dashboard", root_path %>
      
      <%= menu_item "Courses", courses_path %>

      <% if can? :manage, User %>
          <%= menu_item "Manage User", users_path %>
      <% end %>
      
      <%= menu_item "Logout", destroy_user_session_path , :method => :delete %>
	<% end %>    
  </div>
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    
      <h4>Profile</h4>
  </div>
  
  <div class="col-md-2"></div>
</div>
<br>
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <table class="table">
      <tr>
    	<th><h5>Email   </h5></th>
    	
    	<td><h5><%= @user.email %></h5></td>
      </tr>
      <tr>
      	<th><h5>Role    </h5>
      	
      	<td><h5><%= @user.role %></h5></td>
      </tr>
	</table>
  </div>
  
  <div class="col-md-2"></div>
</div>